version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_vtb
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ['CMD','pg_isready','-U', 'postgres']
      interval: 5s
      timeout: 20s
      retries: 5
  app:
    build:
      context: .
      dockerfile: DOCKERFILE
    env_file:
      - etc/config.env
    container_name: vtb_app
    command: [ "/fastapi_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db
