"""add credits

Revision ID: 3f577bb313a9
Revises: f4f1857e30a3
Create Date: 2023-10-14 14:13:50.517445

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3f577bb313a9"
down_revision = "f4f1857e30a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("offices", sa.Column("Consultation", sa.Boolean(), nullable=True))
    op.add_column("offices", sa.Column("issuing", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("offices", "issuing")
    op.drop_column("offices", "Consultation")
    # ### end Alembic commands ###
