"""add atms

Revision ID: 872ea3fd573e
Revises: 0bc6a73b2d63
Create Date: 2023-10-14 09:34:43.385011

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "872ea3fd573e"
down_revision = "0bc6a73b2d63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "atms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("allDay", sa.Boolean(), nullable=True),
        sa.Column("wheelchair", sa.Boolean(), nullable=True),
        sa.Column("blind", sa.Boolean(), nullable=True),
        sa.Column("nfcForBankCards", sa.Boolean(), nullable=True),
        sa.Column("qrRead", sa.Boolean(), nullable=True),
        sa.Column("supportsUsd", sa.Boolean(), nullable=True),
        sa.Column("supportsChargeRub", sa.Boolean(), nullable=True),
        sa.Column("supportsEur", sa.Boolean(), nullable=True),
        sa.Column("supportsRub", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("atms")
    # ### end Alembic commands ###
