"""init

Revision ID: df5a2fdf5dc7
Revises: cfd11e8f0eb7
Create Date: 2023-10-14 00:37:25.712793

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "df5a2fdf5dc7"
down_revision = "cfd11e8f0eb7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("admin_role_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
