"""add cards

Revision ID: f4f1857e30a3
Revises: 872ea3fd573e
Create Date: 2023-10-14 11:19:53.974669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f1857e30a3'
down_revision = '872ea3fd573e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('credit_card', sa.Boolean(), nullable=True))
    op.add_column('offices', sa.Column('debit_card', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offices', 'debit_card')
    op.drop_column('offices', 'credit_card')
    # ### end Alembic commands ###
